include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    directives_ordering: false

analyzer:
  exclude:
    - '**.config.dart'
    - '**.freezed.dart'
    - '**.g.dart'
